-- ========================================================
-- DATABASE SCHEMA FOR QUIZ APPLICATION
-- Author: Nikhil Kumar
-- Description: Tables for Employee, Quiz Authorization,
--              Quiz Requests, Questions, and Answers
-- ========================================================

-- Employee Master Table
CREATE TABLE ERP_HR_DAT (
    EMP_NO INT PRIMARY KEY,              -- Employee number (manually assigned)
    EMP_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    DEPT VARCHAR(100),
    GRADE VARCHAR(10),
    DESIGNATION VARCHAR(100),
    LOCATION VARCHAR(100),
    PASSWORD VARCHAR(255) NOT NULL      -- Stored as hashed string
);

-- Authorization Table for Admin Privileges
CREATE TABLE QUIZ_AUTHORIZATION (
    EMP_NO INT NOT NULL,
    AUTHORIZED_ON DATETIME NOT NULL,
    AUTHORIZED_BY INT NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL CHECK (IS_ACTIVE IN (0, 1)),

    FOREIGN KEY (EMP_NO) REFERENCES ERP_HR_DAT(EMP_NO),
    FOREIGN KEY (AUTHORIZED_BY) REFERENCES ERP_HR_DAT(EMP_NO)
);

-- Quiz Request Table (Submitted by Users)
CREATE TABLE QUIZ_REQUEST (
    QUIZ_ID INT AUTO_INCREMENT PRIMARY KEY,
    QUIZ_TITLE VARCHAR(200) NOT NULL,
    QUIZ_DESCRIPTION VARCHAR(500),
    QUIZ_START_TIME DATETIME NOT NULL,
    QUIZ_END_TIME DATETIME NOT NULL,
    QUIZ_DATE DATE NOT NULL,
    QUIZ_DURATION INT NOT NULL, -- in minutes
    QUIZ_STATUS VARCHAR(20) NOT NULL CHECK (QUIZ_STATUS IN ('Pending', 'Approved', 'Rejected')),
    REQUESTED_BY INT NOT NULL,
    ACTIONED_BY INT,
    ADMIN_COMMENTS VARCHAR(500),
    DATE_SUBMITTED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATE_REVIEWED DATETIME,
    DEPARTMENT VARCHAR(100),
    NUM_RANDOM_QUESTIONS INT,

    FOREIGN KEY (REQUESTED_BY) REFERENCES ERP_HR_DAT(EMP_NO)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Questions Table for Each Quiz
CREATE TABLE QUIZ_QUESTIONS (
    QUESTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    QUIZ_ID INT NOT NULL,
    QUESTION TEXT NOT NULL,
    OPTION_A VARCHAR(200) NOT NULL,
    OPTION_B VARCHAR(200) NOT NULL,
    OPTION_C VARCHAR(200) NOT NULL,
    OPTION_D VARCHAR(200) NOT NULL,
    CORRECT_OPTION CHAR(1) NOT NULL CHECK (CORRECT_OPTION IN ('A','B','C','D')),

    FOREIGN KEY (QUIZ_ID) REFERENCES QUIZ_REQUEST(QUIZ_ID)
);

-- Answers Submitted by Users
CREATE TABLE QUIZ_ANSWER (
    USER_ID INT NOT NULL,
    QUIZ_ID INT NOT NULL,
    QUESTION_ID INT NOT NULL,
    SELECTED_OPTION CHAR(1) NOT NULL CHECK (SELECTED_OPTION IN ('A','B','C','D')),
    ATTEMPTED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (USER_ID, QUIZ_ID, QUESTION_ID),

    FOREIGN KEY (USER_ID) REFERENCES ERP_HR_DAT(EMP_NO),
    FOREIGN KEY (QUIZ_ID) REFERENCES QUIZ_REQUEST(QUIZ_ID),
    FOREIGN KEY (QUESTION_ID) REFERENCES QUIZ_QUESTIONS(QUESTION_ID)
);
